# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c9deae18c9c4f2fc9570afe4117f1dc649d86157bddcd72e466bf88936ebd0bba69281c44277cdf1c74fa2105307b5b6b262b59b0611249827ce99e67e72eb4

test:
  secret_key_base: 252bb23be91756a90ddc792a854c37fbcca5a266b9adfa8b47c9635dd93f488496d5b8b216bac765b2bb50f2dd5248ca1ab0978036a9bd4145e6b08368a756a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
